In [8]:
import pandas as pd

In [18]:
df = pd.read_csv("911_raw_data.csv")
df.head()

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
0,2025 / 03,Aggregate,Combined average response time to life threate...,Brooklyn,13615,567.01
1,2025 / 03,Aggregate,Combined average response time to life threate...,Bronx,11039,683.05
2,2025 / 03,Aggregate,Combined average response time to life threate...,Manhattan,10868,642.23
3,2025 / 03,Aggregate,Combined average response time to life threate...,Queens,9819,601.25
4,2025 / 03,Aggregate,Combined average response time to life threate...,Staten Island,2398,550.99

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10166 entries, 0 to 10165
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Month Name      10166 non-null  object
 1   Agency          10166 non-null  object
 2   Description     10166 non-null  object
 3   Borough         10166 non-null  object
 4   # of Incidents  10166 non-null  int64
 5   Response Times  10166 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 476.7+ KB

In [42]:
df["Description"].value_counts()

Description
Combined average response time to life threatening medical emergencies by ambulance and fire units                                                         822
Average response time to life threatening medical emergencies by ambulance units                                                                           822
Average response time to life threatening and non-life threatening medical emergencies by ambulance units combined                                         822
Average response time to non-fire emergencies                                                                                                              820
Average response time to life threatening medical emergencies by fire units                                                                                817
Percentage of response time of less than 10 minutes to Advanced Life Support medical emergencies by Advanced Life Support ambulances                       804
Average response time to segment 1 medical emergencies, as defined by the department, including cardiac arrest and choking incidents by ambulance units    786
Percentage of response time to structural and non-structural fires by fire units less than 5 minutes                                                       754
Percentage of response time to structural and non-structural fires by fire units between 5 and 10 minutes                                                  754
Percentage of response time to structural and non-structural fires by fire units between 10 and 20 minutes                                                 754
Percentage of response time to structural and non-structural fires by fire units more than 20 minutes                                                      754
Average response time to non-structural fires                                                                                                              738
Average response time to structural fires                                                                                                                  719
Name: count, dtype: int64

In [44]:
df["Borough"].value_counts()

Borough
Manhattan        1778
Queens           1778
Brooklyn         1777
Bronx            1777
Staten Island    1777
Unspecified      1279
Name: count, dtype: int64

In [74]:
df.groupby("Borough")

MANHATTAN

In [164]:
## this is the filtered df for manhattan ems 
man_ems_df= df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and Borough == 'Manhattan' \
        and Agency == 'EMS'").sort_values(by="Description")
man_ems_df

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
16,2025 / 03,EMS,Average response time to life threatening and ...,Manhattan,21793,996.31
93,2025 / 02,EMS,Average response time to life threatening and ...,Manhattan,19535,1118.38
170,2025 / 01,EMS,Average response time to life threatening and ...,Manhattan,22131,1061.35
15,2025 / 03,EMS,Average response time to life threatening medi...,Manhattan,9900,666.90
92,2025 / 02,EMS,Average response time to life threatening medi...,Manhattan,8887,703.45
169,2025 / 01,EMS,Average response time to life threatening medi...,Manhattan,9958,674.91
14,2025 / 03,EMS,Average response time to segment 1 medical eme...,Manhattan,405,558.83
91,2025 / 02,EMS,Average response time to segment 1 medical eme...,Manhattan,391,529.50
168,2025 / 01,EMS,Average response time to segment 1 medical eme...,Manhattan,475,512.74
17,2025 / 03,EMS,Percentage of response time of less than 10 mi...,Manhattan,4841,47.72
94,2025 / 02,EMS,Percentage of response time of less than 10 mi...,Manhattan,4546,46.22
171,2025 / 01,EMS,Percentage of response time of less than 10 mi...,Manhattan,5201,47.68

In [162]:
## just checking frst three rows
df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and Borough == 'Manhattan' \
        and Agency == 'EMS'").sort_values(by="Description").head(3)

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
16,2025 / 03,EMS,Average response time to life threatening and ...,Manhattan,21793,996.31
93,2025 / 02,EMS,Average response time to life threatening and ...,Manhattan,19535,1118.38
170,2025 / 01,EMS,Average response time to life threatening and ...,Manhattan,22131,1061.35

In [197]:
## final response times for manhattan ems!
## dividing final by 60 to get minutes instead of seconds. REMEMBER- to check percentage- remove /60  
man_ems_times_df = man_ems_df.groupby(['Description', 'Month Name'])['Response Times'].mean().unstack()
man_ems_times_df / 60

Month Name,2025 / 01,2025 / 02,2025 / 03
Description,,,
Average response time to life threatening and non-life threatening medical emergencies by ambulance units combined,17.689167,18.639667,16.605167
Average response time to life threatening medical emergencies by ambulance units,11.248500,11.724167,11.115000
"Average response time to segment 1 medical emergencies, as defined by the department, including cardiac arrest and choking incidents by ambulance units",8.545667,8.825000,9.313833
Percentage of response time of less than 10 minutes to Advanced Life Support medical emergencies by Advanced Life Support ambulances,0.794667,0.770333,0.795333

In [170]:
## Now do the same for manhattan fdny and manhattan aggregate

In [175]:
man_fdny_df= df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and Borough == 'Manhattan' \
        and Agency == 'FDNY'").sort_values(by="Description")
man_fdny_df

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
126,2025 / 02,FDNY,Average response time to life threatening medi...,Manhattan,2365,620.74
49,2025 / 03,FDNY,Average response time to life threatening medi...,Manhattan,2584,600.67
203,2025 / 01,FDNY,Average response time to life threatening medi...,Manhattan,2567,606.47
48,2025 / 03,FDNY,Average response time to non-fire emergencies,Manhattan,5848,619.58
202,2025 / 01,FDNY,Average response time to non-fire emergencies,Manhattan,6059,630.02
125,2025 / 02,FDNY,Average response time to non-fire emergencies,Manhattan,5399,657.18
47,2025 / 03,FDNY,Average response time to non-structural fires,Manhattan,164,383.27
201,2025 / 01,FDNY,Average response time to non-structural fires,Manhattan,209,383.40
124,2025 / 02,FDNY,Average response time to non-structural fires,Manhattan,266,737.34
200,2025 / 01,FDNY,Average response time to structural fires,Manhattan,252,301.79
46,2025 / 03,FDNY,Average response time to structural fires,Manhattan,244,301.41
123,2025 / 02,FDNY,Average response time to structural fires,Manhattan,218,313.67
206,2025 / 01,FDNY,Percentage of response time to structural and ...,Manhattan,461,2.82
129,2025 / 02,FDNY,Percentage of response time to structural and ...,Manhattan,484,3.10
52,2025 / 03,FDNY,Percentage of response time to structural and ...,Manhattan,408,2.94
128,2025 / 02,FDNY,Percentage of response time to structural and ...,Manhattan,484,59.92
51,2025 / 03,FDNY,Percentage of response time to structural and ...,Manhattan,408,57.11
205,2025 / 01,FDNY,Percentage of response time to structural and ...,Manhattan,461,52.49
127,2025 / 02,FDNY,Percentage of response time to structural and ...,Manhattan,484,35.95
50,2025 / 03,FDNY,Percentage of response time to structural and ...,Manhattan,408,39.95
204,2025 / 01,FDNY,Percentage of response time to structural and ...,Manhattan,461,44.25
130,2025 / 02,FDNY,Percentage of response time to structural and ...,Manhattan,484,1.03
53,2025 / 03,FDNY,Percentage of response time to structural and ...,Manhattan,408,0.00
207,2025 / 01,FDNY,Percentage of response time to structural and ...,Manhattan,461,0.43

In [195]:
## final response times for manhattan fdny
man_fdny_times_df = man_fdny_df.groupby(['Description', 'Month Name'])['Response Times'].mean().unstack()
man_fdny_times_df /60

Month Name,2025 / 01,2025 / 02,2025 / 03
Description,,,
Average response time to life threatening medical emergencies by fire units,10.107833,10.345667,10.011167
Average response time to non-fire emergencies,10.500333,10.953000,10.326333
Average response time to non-structural fires,6.390000,12.289000,6.387833
Average response time to structural fires,5.029833,5.227833,5.023500
Percentage of response time to structural and non-structural fires by fire units between 10 and 20 minutes,0.047000,0.051667,0.049000
Percentage of response time to structural and non-structural fires by fire units between 5 and 10 minutes,0.874833,0.998667,0.951833
Percentage of response time to structural and non-structural fires by fire units less than 5 minutes,0.737500,0.599167,0.665833
Percentage of response time to structural and non-structural fires by fire units more than 20 minutes,0.007167,0.017167,0.000000

In [183]:
## manhattan aggregate
man_agg_df= df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and Borough == 'Manhattan' \
        and Agency == 'Aggregate'").sort_values(by="Description")
man_agg_df

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
2,2025 / 03,Aggregate,Combined average response time to life threate...,Manhattan,10868,642.23
79,2025 / 02,Aggregate,Combined average response time to life threate...,Manhattan,9758,681.85
156,2025 / 01,Aggregate,Combined average response time to life threate...,Manhattan,10888,654.27

In [199]:

man_agg_times_df = man_agg_df.groupby(['Description', 'Month Name'])['Response Times'].mean().unstack()
man_agg_times_df /60

Month Name,2025 / 01,2025 / 02,2025 / 03
Description,,,
Combined average response time to life threatening medical emergencies by ambulance and fire units,10.9045,11.364167,10.703833

BROOKLYN

In [218]:
## brooklyn aggregate
bk_agg_df= df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and Borough == 'Brooklyn' \
        and Agency == 'Aggregate'").sort_values(by="Description")
bk_agg_df

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
0,2025 / 03,Aggregate,Combined average response time to life threate...,Brooklyn,13615,567.01
77,2025 / 02,Aggregate,Combined average response time to life threate...,Brooklyn,12644,591.59
154,2025 / 01,Aggregate,Combined average response time to life threate...,Brooklyn,14592,601.53

In [222]:
bk_agg_times_df = bk_agg_df.groupby(['Description', 'Month Name'])['Response Times'].mean().unstack()
bk_agg_times_df / 60

Month Name,2025 / 01,2025 / 02,2025 / 03
Description,,,
Combined average response time to life threatening medical emergencies by ambulance and fire units,10.0255,9.859833,9.450167

In [204]:
## this is the filtered df for brooklyn ems 
bk_ems_df= df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and Borough == 'Brooklyn' \
        and Agency == 'EMS'").sort_values(by="Description")
bk_ems_df

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
8,2025 / 03,EMS,Average response time to life threatening and ...,Brooklyn,27322,824.15
85,2025 / 02,EMS,Average response time to life threatening and ...,Brooklyn,24916,917.55
162,2025 / 01,EMS,Average response time to life threatening and ...,Brooklyn,28566,946.92
7,2025 / 03,EMS,Average response time to life threatening medi...,Brooklyn,12750,610.72
84,2025 / 02,EMS,Average response time to life threatening medi...,Brooklyn,11928,640.39
161,2025 / 01,EMS,Average response time to life threatening medi...,Brooklyn,13785,647.31
6,2025 / 03,EMS,Average response time to segment 1 medical eme...,Brooklyn,601,515.47
83,2025 / 02,EMS,Average response time to segment 1 medical eme...,Brooklyn,575,514.12
160,2025 / 01,EMS,Average response time to segment 1 medical eme...,Brooklyn,705,554.81
9,2025 / 03,EMS,Percentage of response time of less than 10 mi...,Brooklyn,5683,50.66
86,2025 / 02,EMS,Percentage of response time of less than 10 mi...,Brooklyn,5438,47.11
163,2025 / 01,EMS,Percentage of response time of less than 10 mi...,Brooklyn,6269,45.70

In [208]:
## final brooklyn ems response times 
bk_ems_times_df = bk_ems_df.groupby(['Description', 'Month Name'])['Response Times'].mean().unstack()
bk_ems_times_df / 60

Month Name,2025 / 01,2025 / 02,2025 / 03
Description,,,
Average response time to life threatening and non-life threatening medical emergencies by ambulance units combined,15.782000,15.292500,13.735833
Average response time to life threatening medical emergencies by ambulance units,10.788500,10.673167,10.178667
"Average response time to segment 1 medical emergencies, as defined by the department, including cardiac arrest and choking incidents by ambulance units",9.246833,8.568667,8.591167
Percentage of response time of less than 10 minutes to Advanced Life Support medical emergencies by Advanced Life Support ambulances,0.761667,0.785167,0.844333

In [212]:
## this is the filtered df for brooklyn fdny 
bk_fdny_df= df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and Borough == 'Brooklyn' \
        and Agency == 'FDNY'").sort_values(by="Description")
bk_fdny_df

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
110,2025 / 02,FDNY,Average response time to life threatening medi...,Brooklyn,3757,536.29
33,2025 / 03,FDNY,Average response time to life threatening medi...,Brooklyn,4006,532.50
187,2025 / 01,FDNY,Average response time to life threatening medi...,Brooklyn,4363,555.62
32,2025 / 03,FDNY,Average response time to non-fire emergencies,Brooklyn,7874,591.76
186,2025 / 01,FDNY,Average response time to non-fire emergencies,Brooklyn,8770,591.39
109,2025 / 02,FDNY,Average response time to non-fire emergencies,Brooklyn,7349,572.10
31,2025 / 03,FDNY,Average response time to non-structural fires,Brooklyn,223,353.49
185,2025 / 01,FDNY,Average response time to non-structural fires,Brooklyn,484,390.81
108,2025 / 02,FDNY,Average response time to non-structural fires,Brooklyn,549,360.83
184,2025 / 01,FDNY,Average response time to structural fires,Brooklyn,379,275.01
30,2025 / 03,FDNY,Average response time to structural fires,Brooklyn,341,270.79
107,2025 / 02,FDNY,Average response time to structural fires,Brooklyn,309,264.72
190,2025 / 01,FDNY,Percentage of response time to structural and ...,Brooklyn,863,1.04
113,2025 / 02,FDNY,Percentage of response time to structural and ...,Brooklyn,858,2.56
36,2025 / 03,FDNY,Percentage of response time to structural and ...,Brooklyn,564,1.42
112,2025 / 02,FDNY,Percentage of response time to structural and ...,Brooklyn,858,45.69
35,2025 / 03,FDNY,Percentage of response time to structural and ...,Brooklyn,564,38.12
189,2025 / 01,FDNY,Percentage of response time to structural and ...,Brooklyn,863,46.35
111,2025 / 02,FDNY,Percentage of response time to structural and ...,Brooklyn,858,51.28
34,2025 / 03,FDNY,Percentage of response time to structural and ...,Brooklyn,564,60.11
188,2025 / 01,FDNY,Percentage of response time to structural and ...,Brooklyn,863,51.68
114,2025 / 02,FDNY,Percentage of response time to structural and ...,Brooklyn,858,0.47
37,2025 / 03,FDNY,Percentage of response time to structural and ...,Brooklyn,564,0.35
191,2025 / 01,FDNY,Percentage of response time to structural and ...,Brooklyn,863,0.93

In [216]:
## final brooklyn fdny response times 
bk_fdny_times_df = bk_fdny_df.groupby(['Description', 'Month Name'])['Response Times'].mean().unstack()
bk_fdny_times_df / 60

Month Name,2025 / 01,2025 / 02,2025 / 03
Description,,,
Average response time to life threatening medical emergencies by fire units,9.260333,8.938167,8.875000
Average response time to non-fire emergencies,9.856500,9.535000,9.862667
Average response time to non-structural fires,6.513500,6.013833,5.891500
Average response time to structural fires,4.583500,4.412000,4.513167
Percentage of response time to structural and non-structural fires by fire units between 10 and 20 minutes,0.017333,0.042667,0.023667
Percentage of response time to structural and non-structural fires by fire units between 5 and 10 minutes,0.772500,0.761500,0.635333
Percentage of response time to structural and non-structural fires by fire units less than 5 minutes,0.861333,0.854667,1.001833
Percentage of response time to structural and non-structural fires by fire units more than 20 minutes,0.015500,0.007833,0.005833

QUEENS

In [227]:
## queens aggregate
qns_agg_df= df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and Borough == 'Queens' \
        and Agency == 'Aggregate'").sort_values(by="Description")
qns_agg_df

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
3,2025 / 03,Aggregate,Combined average response time to life threate...,Queens,9819,601.25
80,2025 / 02,Aggregate,Combined average response time to life threate...,Queens,8944,628.68
157,2025 / 01,Aggregate,Combined average response time to life threate...,Queens,10413,620.68

In [231]:
## final queens aggregate response times
qns_agg_times_df = qns_agg_df.groupby(['Description', 'Month Name'])['Response Times'].mean().unstack()
qns_agg_times_df / 60

Month Name,2025 / 01,2025 / 02,2025 / 03
Description,,,
Combined average response time to life threatening medical emergencies by ambulance and fire units,10.344667,10.478,10.020833

In [235]:
## this is the filtered df for queens ems 
qns_ems_df= df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and Borough == 'Queens' \
        and Agency == 'EMS'").sort_values(by="Description")
qns_ems_df

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
20,2025 / 03,EMS,Average response time to life threatening and ...,Queens,20147,823.69
97,2025 / 02,EMS,Average response time to life threatening and ...,Queens,18274,893.85
174,2025 / 01,EMS,Average response time to life threatening and ...,Queens,21076,889.18
19,2025 / 03,EMS,Average response time to life threatening medi...,Queens,9014,650.15
96,2025 / 02,EMS,Average response time to life threatening medi...,Queens,8216,676.00
173,2025 / 01,EMS,Average response time to life threatening medi...,Queens,9645,670.11
18,2025 / 03,EMS,Average response time to segment 1 medical eme...,Queens,509,553.39
95,2025 / 02,EMS,Average response time to segment 1 medical eme...,Queens,504,571.58
172,2025 / 01,EMS,Average response time to segment 1 medical eme...,Queens,569,576.36
21,2025 / 03,EMS,Percentage of response time of less than 10 mi...,Queens,3185,40.57
98,2025 / 02,EMS,Percentage of response time of less than 10 mi...,Queens,3251,37.28
175,2025 / 01,EMS,Percentage of response time of less than 10 mi...,Queens,3728,38.63

In [239]:
qns_ems_times_df = qns_ems_df.groupby(['Description', 'Month Name'])['Response Times'].mean().unstack()
qns_ems_times_df / 60

Month Name,2025 / 01,2025 / 02,2025 / 03
Description,,,
Average response time to life threatening and non-life threatening medical emergencies by ambulance units combined,14.819667,14.897500,13.728167
Average response time to life threatening medical emergencies by ambulance units,11.168500,11.266667,10.835833
"Average response time to segment 1 medical emergencies, as defined by the department, including cardiac arrest and choking incidents by ambulance units",9.606000,9.526333,9.223167
Percentage of response time of less than 10 minutes to Advanced Life Support medical emergencies by Advanced Life Support ambulances,0.643833,0.621333,0.676167

In [249]:
## this is the filtered df for queens fdny 
qns_fdny_df= df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and Borough == 'Queens' \
        and Agency == 'FDNY'").sort_values(by="Description")
qns_fdny_df

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
134,2025 / 02,FDNY,Average response time to life threatening medi...,Queens,2556,569.45
57,2025 / 03,FDNY,Average response time to life threatening medi...,Queens,2886,555.97
211,2025 / 01,FDNY,Average response time to life threatening medi...,Queens,3076,568.11
56,2025 / 03,FDNY,Average response time to non-fire emergencies,Queens,5422,637.59
210,2025 / 01,FDNY,Average response time to non-fire emergencies,Queens,5790,637.10
133,2025 / 02,FDNY,Average response time to non-fire emergencies,Queens,5009,639.58
55,2025 / 03,FDNY,Average response time to non-structural fires,Queens,183,444.70
209,2025 / 01,FDNY,Average response time to non-structural fires,Queens,200,412.79
132,2025 / 02,FDNY,Average response time to non-structural fires,Queens,320,432.00
208,2025 / 01,FDNY,Average response time to structural fires,Queens,201,315.02
54,2025 / 03,FDNY,Average response time to structural fires,Queens,201,311.36
131,2025 / 02,FDNY,Average response time to structural fires,Queens,195,318.88
214,2025 / 01,FDNY,Percentage of response time to structural and ...,Queens,401,2.99
137,2025 / 02,FDNY,Percentage of response time to structural and ...,Queens,515,4.47
60,2025 / 03,FDNY,Percentage of response time to structural and ...,Queens,384,4.17
136,2025 / 02,FDNY,Percentage of response time to structural and ...,Queens,515,64.27
59,2025 / 03,FDNY,Percentage of response time to structural and ...,Queens,384,59.64
213,2025 / 01,FDNY,Percentage of response time to structural and ...,Queens,401,59.10
135,2025 / 02,FDNY,Percentage of response time to structural and ...,Queens,515,30.10
58,2025 / 03,FDNY,Percentage of response time to structural and ...,Queens,384,35.42
212,2025 / 01,FDNY,Percentage of response time to structural and ...,Queens,401,37.16
138,2025 / 02,FDNY,Percentage of response time to structural and ...,Queens,515,1.17
61,2025 / 03,FDNY,Percentage of response time to structural and ...,Queens,384,0.78
215,2025 / 01,FDNY,Percentage of response time to structural and ...,Queens,401,0.75

In [253]:
qns_fdny_times_df = qns_fdny_df.groupby(['Description', 'Month Name'])['Response Times'].mean().unstack()
qns_fdny_times_df / 60

Month Name,2025 / 01,2025 / 02,2025 / 03
Description,,,
Average response time to life threatening medical emergencies by fire units,9.468500,9.490833,9.266167
Average response time to non-fire emergencies,10.618333,10.659667,10.626500
Average response time to non-structural fires,6.879833,7.200000,7.411667
Average response time to structural fires,5.250333,5.314667,5.189333
Percentage of response time to structural and non-structural fires by fire units between 10 and 20 minutes,0.049833,0.074500,0.069500
Percentage of response time to structural and non-structural fires by fire units between 5 and 10 minutes,0.985000,1.071167,0.994000
Percentage of response time to structural and non-structural fires by fire units less than 5 minutes,0.619333,0.501667,0.590333
Percentage of response time to structural and non-structural fires by fire units more than 20 minutes,0.012500,0.019500,0.013000

BRONX

In [258]:
## bronx aggregate
bx_agg_df= df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and Borough == 'Bronx' \
        and Agency == 'Aggregate'").sort_values(by="Description")
bx_agg_df

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
1,2025 / 03,Aggregate,Combined average response time to life threate...,Bronx,11039,683.05
78,2025 / 02,Aggregate,Combined average response time to life threate...,Bronx,10562,819.40
155,2025 / 01,Aggregate,Combined average response time to life threate...,Bronx,12405,873.22

In [262]:
## final bronx aggregate response times
bx_agg_times_df = bx_agg_df.groupby(['Description', 'Month Name'])['Response Times'].mean().unstack()
bx_agg_times_df / 60

Month Name,2025 / 01,2025 / 02,2025 / 03
Description,,,
Combined average response time to life threatening medical emergencies by ambulance and fire units,14.553667,13.656667,11.384167

In [266]:
## filtered df for bronx ems 
bx_ems_df= df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and Borough == 'Bronx' \
        and Agency == 'EMS'").sort_values(by="Description")
bx_ems_df

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
12,2025 / 03,EMS,Average response time to life threatening and ...,Bronx,23741,1002.71
89,2025 / 02,EMS,Average response time to life threatening and ...,Bronx,21251,1396.82
166,2025 / 01,EMS,Average response time to life threatening and ...,Bronx,24541,1619.23
11,2025 / 03,EMS,Average response time to life threatening medi...,Bronx,9664,713.07
88,2025 / 02,EMS,Average response time to life threatening medi...,Bronx,9365,835.72
165,2025 / 01,EMS,Average response time to life threatening medi...,Bronx,10896,873.96
10,2025 / 03,EMS,Average response time to segment 1 medical eme...,Bronx,443,559.89
87,2025 / 02,EMS,Average response time to segment 1 medical eme...,Bronx,442,633.33
164,2025 / 01,EMS,Average response time to segment 1 medical eme...,Bronx,462,655.02
13,2025 / 03,EMS,Percentage of response time of less than 10 mi...,Bronx,3444,28.57
90,2025 / 02,EMS,Percentage of response time of less than 10 mi...,Bronx,3212,25.75
167,2025 / 01,EMS,Percentage of response time of less than 10 mi...,Bronx,3704,22.95

In [270]:
## final bronx ems response times
bx_ems_times_df = bx_ems_df.groupby(['Description', 'Month Name'])['Response Times'].mean().unstack()
bx_ems_times_df / 60

Month Name,2025 / 01,2025 / 02,2025 / 03
Description,,,
Average response time to life threatening and non-life threatening medical emergencies by ambulance units combined,26.987167,23.280333,16.711833
Average response time to life threatening medical emergencies by ambulance units,14.566000,13.928667,11.884500
"Average response time to segment 1 medical emergencies, as defined by the department, including cardiac arrest and choking incidents by ambulance units",10.917000,10.555500,9.331500
Percentage of response time of less than 10 minutes to Advanced Life Support medical emergencies by Advanced Life Support ambulances,0.382500,0.429167,0.476167

In [274]:
## filtered df for bronx fdny 
bx_fdny_df= df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and Borough == 'Bronx' \
        and Agency == 'FDNY'").sort_values(by="Description")
bx_fdny_df

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
118,2025 / 02,FDNY,Average response time to life threatening medi...,Bronx,2519,750.61
41,2025 / 03,FDNY,Average response time to life threatening medi...,Bronx,2471,643.13
195,2025 / 01,FDNY,Average response time to life threatening medi...,Bronx,3036,750.18
40,2025 / 03,FDNY,Average response time to non-fire emergencies,Bronx,6071,699.35
194,2025 / 01,FDNY,Average response time to non-fire emergencies,Bronx,6967,847.41
117,2025 / 02,FDNY,Average response time to non-fire emergencies,Bronx,5710,831.42
39,2025 / 03,FDNY,Average response time to non-structural fires,Bronx,122,403.43
193,2025 / 01,FDNY,Average response time to non-structural fires,Bronx,172,428.27
116,2025 / 02,FDNY,Average response time to non-structural fires,Bronx,196,407.48
192,2025 / 01,FDNY,Average response time to structural fires,Bronx,320,323.99
38,2025 / 03,FDNY,Average response time to structural fires,Bronx,257,318.97
115,2025 / 02,FDNY,Average response time to structural fires,Bronx,258,691.46
198,2025 / 01,FDNY,Percentage of response time to structural and ...,Bronx,492,3.46
121,2025 / 02,FDNY,Percentage of response time to structural and ...,Bronx,454,3.30
44,2025 / 03,FDNY,Percentage of response time to structural and ...,Bronx,379,2.64
120,2025 / 02,FDNY,Percentage of response time to structural and ...,Bronx,454,65.64
43,2025 / 03,FDNY,Percentage of response time to structural and ...,Bronx,379,59.63
197,2025 / 01,FDNY,Percentage of response time to structural and ...,Bronx,492,64.43
119,2025 / 02,FDNY,Percentage of response time to structural and ...,Bronx,454,30.18
42,2025 / 03,FDNY,Percentage of response time to structural and ...,Bronx,379,37.73
196,2025 / 01,FDNY,Percentage of response time to structural and ...,Bronx,492,31.91
122,2025 / 02,FDNY,Percentage of response time to structural and ...,Bronx,454,0.88
45,2025 / 03,FDNY,Percentage of response time to structural and ...,Bronx,379,0.00
199,2025 / 01,FDNY,Percentage of response time to structural and ...,Bronx,492,0.20

In [278]:
## final bronx fdny response times
bx_fdny_times_df = bx_fdny_df.groupby(['Description', 'Month Name'])['Response Times'].mean().unstack()
bx_fdny_times_df / 60

Month Name,2025 / 01,2025 / 02,2025 / 03
Description,,,
Average response time to life threatening medical emergencies by fire units,12.503000,12.510167,10.718833
Average response time to non-fire emergencies,14.123500,13.857000,11.655833
Average response time to non-structural fires,7.137833,6.791333,6.723833
Average response time to structural fires,5.399833,11.524333,5.316167
Percentage of response time to structural and non-structural fires by fire units between 10 and 20 minutes,0.057667,0.055000,0.044000
Percentage of response time to structural and non-structural fires by fire units between 5 and 10 minutes,1.073833,1.094000,0.993833
Percentage of response time to structural and non-structural fires by fire units less than 5 minutes,0.531833,0.503000,0.628833
Percentage of response time to structural and non-structural fires by fire units more than 20 minutes,0.003333,0.014667,0.000000

STATEN ISLAND

In [285]:
## staten island aggregate
si_agg_df= df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and \
        Borough == 'Staten Island' \
        and Agency == 'Aggregate'").sort_values(by="Description")
si_agg_df

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
4,2025 / 03,Aggregate,Combined average response time to life threate...,Staten Island,2398,550.99
81,2025 / 02,Aggregate,Combined average response time to life threate...,Staten Island,2115,556.48
158,2025 / 01,Aggregate,Combined average response time to life threate...,Staten Island,2478,548.46

In [289]:
## final si aggregate response times
si_agg_times_df = si_agg_df.groupby(['Description', 'Month Name'])['Response Times'].mean().unstack()
si_agg_times_df / 60

Month Name,2025 / 01,2025 / 02,2025 / 03
Description,,,
Combined average response time to life threatening medical emergencies by ambulance and fire units,9.141,9.274667,9.183167

In [293]:
## staten island ems
si_ems_df= df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and \
        Borough == 'Staten Island' \
        and Agency == 'EMS'").sort_values(by="Description")
si_ems_df

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
24,2025 / 03,EMS,Average response time to life threatening and ...,Staten Island,4455,709.42
101,2025 / 02,EMS,Average response time to life threatening and ...,Staten Island,3947,705.42
178,2025 / 01,EMS,Average response time to life threatening and ...,Staten Island,4562,729.23
23,2025 / 03,EMS,Average response time to life threatening medi...,Staten Island,2263,605.51
100,2025 / 02,EMS,Average response time to life threatening medi...,Staten Island,2009,612.95
177,2025 / 01,EMS,Average response time to life threatening medi...,Staten Island,2353,603.05
22,2025 / 03,EMS,Average response time to segment 1 medical eme...,Staten Island,119,556.82
99,2025 / 02,EMS,Average response time to segment 1 medical eme...,Staten Island,129,519.98
176,2025 / 01,EMS,Average response time to segment 1 medical eme...,Staten Island,135,543.01
25,2025 / 03,EMS,Percentage of response time of less than 10 mi...,Staten Island,1141,50.04
102,2025 / 02,EMS,Percentage of response time of less than 10 mi...,Staten Island,1066,47.19
179,2025 / 01,EMS,Percentage of response time of less than 10 mi...,Staten Island,1261,51.70

In [297]:
## final si ems response times
si_ems_times_df = si_ems_df.groupby(['Description', 'Month Name'])['Response Times'].mean().unstack()
si_ems_times_df / 60

Month Name,2025 / 01,2025 / 02,2025 / 03
Description,,,
Average response time to life threatening and non-life threatening medical emergencies by ambulance units combined,12.153833,11.757000,11.823667
Average response time to life threatening medical emergencies by ambulance units,10.050833,10.215833,10.091833
"Average response time to segment 1 medical emergencies, as defined by the department, including cardiac arrest and choking incidents by ambulance units",9.050167,8.666333,9.280333
Percentage of response time of less than 10 minutes to Advanced Life Support medical emergencies by Advanced Life Support ambulances,0.861667,0.786500,0.834000

In [301]:
## staten island fdny
si_fdny_df= df.query("(`Month Name` == '2025 / 03' or `Month Name` == '2025 / 02' or `Month Name` == '2025 / 01') and \
        Borough == 'Staten Island' \
        and Agency == 'FDNY'").sort_values(by="Description")
si_fdny_df

,Month Name,Agency,Description,Borough,# of Incidents,Response Times
142,2025 / 02,FDNY,Average response time to life threatening medi...,Staten Island,767,505.42
65,2025 / 03,FDNY,Average response time to life threatening medi...,Staten Island,802,494.92
219,2025 / 01,FDNY,Average response time to life threatening medi...,Staten Island,824,507.62
64,2025 / 03,FDNY,Average response time to non-fire emergencies,Staten Island,1409,564.73
218,2025 / 01,FDNY,Average response time to non-fire emergencies,Staten Island,1468,565.37
141,2025 / 02,FDNY,Average response time to non-fire emergencies,Staten Island,1336,572.22
63,2025 / 03,FDNY,Average response time to non-structural fires,Staten Island,44,337.80
217,2025 / 01,FDNY,Average response time to non-structural fires,Staten Island,27,380.15
140,2025 / 02,FDNY,Average response time to non-structural fires,Staten Island,17,339.59
216,2025 / 01,FDNY,Average response time to structural fires,Staten Island,42,315.31
62,2025 / 03,FDNY,Average response time to structural fires,Staten Island,44,313.91
139,2025 / 02,FDNY,Average response time to structural fires,Staten Island,39,303.82
222,2025 / 01,FDNY,Percentage of response time to structural and ...,Staten Island,69,1.45
145,2025 / 02,FDNY,Percentage of response time to structural and ...,Staten Island,56,1.79
68,2025 / 03,FDNY,Percentage of response time to structural and ...,Staten Island,88,1.14
144,2025 / 02,FDNY,Percentage of response time to structural and ...,Staten Island,56,50.00
67,2025 / 03,FDNY,Percentage of response time to structural and ...,Staten Island,88,52.27
221,2025 / 01,FDNY,Percentage of response time to structural and ...,Staten Island,69,59.42
143,2025 / 02,FDNY,Percentage of response time to structural and ...,Staten Island,56,48.21
66,2025 / 03,FDNY,Percentage of response time to structural and ...,Staten Island,88,46.59
220,2025 / 01,FDNY,Percentage of response time to structural and ...,Staten Island,69,39.13
146,2025 / 02,FDNY,Percentage of response time to structural and ...,Staten Island,56,0.00
69,2025 / 03,FDNY,Percentage of response time to structural and ...,Staten Island,88,0.00
223,2025 / 01,FDNY,Percentage of response time to structural and ...,Staten Island,69,0.00

In [305]:
## final si fdny response times
si_fdny_times_df = si_fdny_df.groupby(['Description', 'Month Name'])['Response Times'].mean().unstack()
si_fdny_times_df / 60

Month Name,2025 / 01,2025 / 02,2025 / 03
Description,,,
Average response time to life threatening medical emergencies by fire units,8.460333,8.423667,8.248667
Average response time to non-fire emergencies,9.422833,9.537000,9.412167
Average response time to non-structural fires,6.335833,5.659833,5.630000
Average response time to structural fires,5.255167,5.063667,5.231833
Percentage of response time to structural and non-structural fires by fire units between 10 and 20 minutes,0.024167,0.029833,0.019000
Percentage of response time to structural and non-structural fires by fire units between 5 and 10 minutes,0.990333,0.833333,0.871167
Percentage of response time to structural and non-structural fires by fire units less than 5 minutes,0.652167,0.803500,0.776500
Percentage of response time to structural and non-structural fires by fire units more than 20 minutes,0.000000,0.000000,0.000000

COMBINED- ALL 5 BOROUGHS

In [312]:
# total_ems_times_df = pd.concat([si_ems_times_df, man_ems_times_df, bk_ems_times_df, qns_ems_times_df, bx_ems_times_df])
# total_ems_times_df - something wrong